# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('rate', models.IntegerField(default=0)),
                ('quan', models.IntegerField(default=1, verbose_name='Quantity')),
                ('date', models.DateField(verbose_name='Bought In')),
            ],
        ),
    ]
