# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bought', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=datetime.datetime(2016, 3, 1, 18, 30, 33, 907448, tzinfo=utc), verbose_name='Sold or Not Sold'),
            preserve_default=False,
        ),
    ]
