# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bought', '0002_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Sold'),
        ),
    ]
