# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 04:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item_bought', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='item_detail_ptr',
        ),
        migrations.AddField(
            model_name='status',
            name='item',
            field=models.ForeignKey(default=datetime.datetime(2016, 2, 27, 4, 21, 18, 609608, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='item_bought.item_detail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item_detail',
            name='date',
            field=models.DateField(verbose_name='date purchased'),
        ),
    ]
