# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 04:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item_bought', '0002_auto_20160227_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='date_sold',
            field=models.DateField(default=datetime.datetime(2016, 2, 27, 4, 23, 18, 396698, tzinfo=utc), primary_key=True, serialize=False, verbose_name='date sold'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_bought.item_detail'),
        ),
    ]
