# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_bought', '0003_auto_20160227_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='sold',
            field=models.CharField(choices=[('Y', 'sold'), ('N', 'not sold')], max_length=1),
        ),
    ]
